#
# log-trace
#

service-name: "gmd"
service-port: 8101
service-version: 1.0

# Logger
logger-exporter: "term"
logger-level: debug
# Tracer
tracer-exporter: "jaeger"
tracer-topic: "gmd-v8"
# Jaeger telemetry
jaeger-tracer:
  content-type: "application/x-thrift"
  endpoint: "http://localhost:14268/api/traces"
zipkin-tracer:
  content-type: "application/json"
  endpoint: "http://localhost:19411/api/v2/spans"
file-tracer:
  path: "./logs"
  folder: "2006-01"
  name: "2006-01-02"
  ext: "trace"


