#
# log-trace
#

# Logger
logger-exporter: "term"
logger-level: debug
# Tracer
tracer-exporter: "jaeger"
tracer-topic: "gmd-v8"
# Jaeger telemetry
jaeger-tracer:
  content-type: "application/x-thrift"
  endpoint: "http://localhost:14268/api/traces"


