adapter: "rocketmq"
account:
  aliyunmns:
    access-id: "KEY"
    access-key: "SEC"
    endpoint: "http://yourid.mns.cn-shanghai.aliyuncs.com/"
    prefix: "X-"
  rocketmq:
    servers:
      - "127.0.0.1:9876"
    brokers:
      - "127.0.0.1:10911"
    prefix: "X-"
    topic-template: "TBW102"
consumer:
producer:


