adapter: "aliyunmns"
account:
  aliyunmns:
    access-id: "YOUR_ACCESS_ID"
    access-key: "YOUR_ACCESS_KEY"
    endpoint: "http://YOUR_ID.mns.cn-shanghai.aliyuncs.com/"
    prefix: "X-"
consumer:
producer:


